-- MySQL Script generated by MySQL Workbench
-- Wed Sep 29 22:06:19 2021
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema committee
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema committee
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `committee` DEFAULT CHARACTER SET utf8 ;
USE `committee` ;

-- -----------------------------------------------------
-- Table `committee`.`users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `committee`.`users` (
  `id` TINYINT(10) NOT NULL,
  `login` VARCHAR(45) NULL,
  `password` VARCHAR(45) NULL,
  `id_role` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `committee`.`grades`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `committee`.`grades` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `subject_first` INT(2) NOT NULL,
  `subject_second` INT(2) NOT NULL,
  `subject_third` INT(2) NOT NULL,
  `sertificate_score` DECIMAL(2,1) NOT NULL,
  `id_users` TINYINT(10) NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_users_UNIQUE` (`id_users` ASC) VISIBLE,
  CONSTRAINT `id_users`
    FOREIGN KEY (`id_users`)
    REFERENCES `committee`.`users` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
